services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env  
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html



volumes:
  mariadb_data:
  wordpress_data:


networks:
  inception:
    driver: bridge